<article class="midl">
<h2><?=$name?></h2>
<p>Вес чёрной дыры: <?=$weight?> масс Солнца</p>
<p>Возраст чёрной дыры: <?=$age?> миллиардов лет</p>
<p>Тип чёрной дыры: <?=$type?> </p>
<p>Галактика:<a href="http://space.tp/galaxy/is?name=<?=$galaxy?>"><?=$galaxy?></a></p>


<?php echo $this->tag->form("blackHole/upd"); ?>
<input type="hidden" name="id" value="<?=$id?>">
<input class="galaxybutton" name="upd" type="submit" value="Изменить">
</form>

<?php echo $this->tag->form("blackHole/delete"); ?>
<input type="hidden" name="name" value="<?=$name?>">
<input class="galaxybutton" name="del" type="submit" value="Удалить">
</form>


</article>