<article class="midl">
<h2>Добавление новой чёрной дыры</h2>

<?php echo $this->tag->form("blackHole/enter"); ?>
<? include "form.phtml";?>
<input class="galaxybutton" onmousedown="search()" name="upd" type="button" value="Добавить">
</form>
<p class="results"></p>

</article>

<script>
function search() {
                var name = document.getElementsByTagName('input')[0].value;
                var weight = document.getElementsByTagName('input')[1].value;
                var age = document.getElementsByTagName('input')[2].value;
                var galaxy = document.getElementsByTagName('select')[0].value;
                var type = document.getElementsByTagName('select')[1].value;
                $.ajax({
                    type: 'POST',
                    url: 'http://space.tp/blackhole/enter',
                    data: 'name=' + name + '&weight=' + weight + '&age=' + age + '&galaxy=' + galaxy + '&type=' + type,
                    success: function(data) {
                        $('.results').html(data);
                    }
                });
            }
</script>

