
<article class="midl">
	<h2>Грузоперевозки</h2>
	<p>Этот раздел посвящён работе с API</p>
	<form name="fupd" action="" method="post">
		<label>Показ таблиц</label><br />
		<select name="table" class="galaxyin">
			<option disabled="disabled">Выберете таблицу</option>
			<option>машины</option>
			<option>марки автомобилей</option>
			<option>водители</option>
			<option>организации</option>
			<option>владельцы</option>
			<option>продукты</option>
			<option>типы продуктов</option>
			<option>груз</option>
			<option>магазины</option>
			<option>перевозки</option>	
		</select>
		<label>Страница</label>
		<input class="galaxyin" type="num" value="1" placeholder="страница" name="size" title="Сюда ввдедите страницу" pattern="[0-9]{1,3}" required>
		<input class="galaxybutton" onclick="search()" name="upd" type="button" value="Изменить">
	</form>
</article>

<article class="results midl"></article>

<script>
function search() {
	 			var page = document.getElementsByTagName('input')[0].value;
                var table = document.getElementsByTagName('select')[0].value;
                $.ajax({
                    type: 'POST',
                    url: 'http://space.tp/mishaapi/select',
                    data: 'table=' + table + '&page=' + page,
                    success: function(data) {
                        $('.results').html(data);
                    }
                });
            }
</script>