<article class="midl">
<h2><a href="http://space.tp/solarsystem/is?name=<?=$name?>"><?=$name?></a></h2>
<p>Галактика:<a href="http://space.tp/galaxy/is?name=<?=$galaxy?>"><?=$galaxy?></a></p>


<?php echo $this->tag->form("solarSystem/upd"); ?>
<input type="hidden" name="id" value="<?=$id?>">
<input class="galaxybutton" name="upd" type="submit" value="Изменить">
</form>

<?php echo $this->tag->form("solarSystem/delete"); ?>
<input type="hidden" name="name" value="<?=$name?>">
<input class="galaxybutton" name="del" type="submit" value="Удалить">
</form>


</article>