<?
	if (isset($solar_systems))
	{
		foreach ($solar_systems->items as $solar_system) {
			$id = $solar_system->id;
			$name = $solar_system->name;
			$galaxy = $solar_system->galaxy->name;

			include "article.phtml";
		}
		echo "<footer>";
		for ($i=1; $i <= $solar_systems->total_pages; $i++) 
			include "foot.phtml";
		echo "</footer>";
	}
	else
		echo '<article class="midl"><h2>СЧёрных дыр нет</h2></article>';
?>