<label for="name">Название скопления*</label><br />
<input class="galaxyin" type="text" value="<?=$name?>" placeholder="Название скопления" name="newname" id="name" title="Сюда введите название" pattern="[a-zA-Zа-яА-ЯЁё0-9]{1}[a-zA-Zа-яА-ЯЁё0-9\s]{0,99}" required><br />
<label for="kol">Кол-во галактик в скоплении</label><br />
<input class="galaxyin" type="num" value="<?=$size?>" placeholder="Кол-во галактик" name="size" id="kol" title="Сюда введите размер" pattern="[0-9]{1,3}" required><br />