<article class="midl">
<h2>Изменение: <?=$name?></h2>

<?php echo $this->tag->form("cluster/updater"); ?>
<? include "form.phtml";?>
<input type="hidden" name="id" value="<?=$id?>">
<input class="galaxybutton" onmousedown="search()" name="upd" type="button" value="Изменить">
</form>
<p class="results"></p>

</article>

<script>
function search() {
	 			var name = document.getElementsByTagName('input')[0].value;
                var kol = document.getElementsByTagName('input')[1].value;
                var id = document.getElementsByTagName('input')[2].value;
                $.ajax({
                    type: 'POST',
                    url: 'http://space.tp/cluster/updater',
                    data: 'name=' + name + '&kol=' + kol + '&id=' + id,
                    success: function(data) {
                        $('.results').html(data);
                    }
                });
            }
</script>