<article class="midl">
<h2>Добавление новой галактики</h2>

<?php echo $this->tag->form("galaxy/enter"); ?>
<? include "form.phtml";?>
<input class="galaxybutton" onmousedown="search()" name="upd" type="button" value="Добавить">
</form>
<p class="results"></p>

</article>

<script>
function search() {
                var name = document.getElementsByTagName('input')[0].value;
                var size = document.getElementsByTagName('input')[1].value;
                var cluster = document.getElementsByTagName('select')[0].value;
                var type = document.getElementsByTagName('select')[1].value;
                $.ajax({
                    type: 'POST',
                    url: 'http://space.tp/galaxy/enter',
                    data: 'name=' + name + '&size=' + size + '&cluster=' + cluster + '&type=' + type,
                    success: function(data) {
                        $('.results').html(data);
                    }
                });
            }
</script>

